### ISSUE TITLE
catch up copilot.vim v 1.13

### ISSUE THREAD

**Issue by rakotomandimby** [copilot-emacs/copilot.el#209]
[copilot.vim 1.13 has several changes](https://github.com/github/copilot.vim/commit/5b19fb001d7f31c4c7c5556d7a97b243bd29f45f) that need to be caught.

I just open this issue for anyone that would take it.

PS: Myself, I am still learning Lisp for Emacs, I wont be ready for that level of task before february 2024.

**Comment by sasinhe** [comment]
I may take on this task if the maintainers allow me.

**Comment by rakotomandimby** [comment]
@sasinhe . please go ahead

**Comment by dannywillems** [comment]
Any update on this?

**Comment by dannywillems** [comment]
While updating, it would be nice to document how to do it for future updates.

**Comment by dannywillems** [comment]
I've made a [PR](https://github.com/copilot-emacs/copilot.el/pull/241) to update to 1.14.0. However, it is simply updating the dist director, not sure it is the only thing to perform.
I'm testing locally in the next days. Let me know if it works for you.
