### ISSUE TITLE
Add a license to copilot.el

### ISSUE THREAD

**Issue by emil-vdw** [copilot-emacs/copilot.el#213]
I think it would be good to add a license to copilot.el, especially now that we are looking to add it to MELPA.

@zerolfx what are your thoughts on this?

**Comment by zerolfx** [comment]
Yes! I believe MIT is a good choice.
The main problem is, should we delete the dist folder before adding the license?

**Comment by rakotomandimby** [comment]
IMHO, `dist` folder is not written by us. 
I think dropping it from our distribution will always be a good choice. We should fetch it after package install. 
But that needs some code to be written for that purpose.

**Comment by emil-vdw** [comment]
This will be a legal requirement since there is no original license and we cannot license their work.

**Comment by kevinji** [comment]
I think this issue can be closed now that #283 has been merged.
