### ISSUE TITLE
Transfer repo to an organization

### ISSUE THREAD

**Issue by zerolfx** [copilot-emacs/copilot.el#221]
I intend to transfer this repository from my personal account to the "copilot-emacs" organization (I've just created it). Because the primary contributors will be members from the community, rather than myself. 

After the transfer, all old links will be automatically redirected to the new repository. See https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#whats-transferred-with-a-repository.

Any suggestions?

**Comment by emil-vdw** [comment]
Sounds good to me. Is this for more decentralized control of the repo or what did you have in mind?

**Comment by zerolfx** [comment]
Transferring is done.

@emil-vdw Sure, I'll assign you as the organization's owner in a few months. After that, you'll have the freedom to invite more contributors, create new repositories within the organization, and so on.
