### ISSUE TITLE
JSONRPC: ‘:events-buffer-scrollback-size’ deprecated. Use ‘events-buffer-config’.

### ISSUE THREAD

**Issue by ethan-leba** [copilot-emacs/copilot.el#225]
As of https://github.com/emacs-mirror/emacs/commit/e0b9944b69ff72923c29756fcfcea9528a3f5069, this line will emit a warning:
https://github.com/zerolfx/copilot.el/blob/653fe7b12990b5b7a050971bed4579022ce4b4f8/copilot.el#L157

Unfortunately `events-buffer-config` was added in the same commit `events-buffer-scrollback-size` was deprecated, so it's not a trivially easy fix. Maybe checking if the `events-buffer-config` slot is present on `jsonrpc-process-connection` would be decent fix?

**Comment by ethan-leba** [comment]
Oops, should've checked the PR tab first: #224

**Comment by emil-vdw** [comment]
Fixed by #224
