### ISSUE TITLE
Copilot.el stop working on Mac OSX recently

### ISSUE THREAD

**Issue by tninja** [copilot-emacs/copilot.el#244]
Thanks a lot for this works, copilot.el has been very useful to me. However, recently, since around Jan 15-20, 2024, Copilot.el stop working on two Macbooks. Wonder if you can give me some hint or suggestion on how to resolve this? When i try to activate it, the exception looks:

Debugger entered--Lisp error: (invalid-slot-name "#<jsonrpc-process-connection jsonrpc-process-conne..." :events-buffer-config)
  signal(invalid-slot-name ("#<jsonrpc-process-connection jsonrpc-process-conne..." :events-buffer-config))
  slot-missing(#<jsonrpc-process-connection jsonrpc-process-connection-1ff8fd5fc7ac> :events-buffer-config oset (:size 0))
  #f(compiled-function (obj slots) "Set slots of OBJ with SLOTS which is a list of name/value pairs.\nCalled from the constructor routine." #<bytecode -0xa6b29f4507f89e4>)(#<jsonrpc-process-connection jsonrpc-process-connection-1ff8fd5fc7ac> (:name "copilot" :events-buffer-config (:size 0) :notification-dispatcher copilot--handle-notification :process #<process copilot agent>))
  apply(#f(compiled-function (obj slots) "Set slots of OBJ with SLOTS which is a list of name/value pairs.\nCalled from the constructor routine." #<bytecode -0xa6b29f4507f89e4>) #<jsonrpc-process-connection jsonrpc-process-connection-1ff8fd5fc7ac> (:name "copilot" :events-buffer-config (:size 0) :notification-dispatcher copilot--handle-notification :process #<process copilot agent>))
  shared-initialize(#<jsonrpc-process-connection jsonrpc-process-connection-1ff8fd5fc7ac> (:name "copilot" :events-buffer-config (:size 0) :notification-dispatcher copilot--handle-notification :process #<process copilot agent>))
  #f(compiled-function (this &optional args) "Construct the new object THIS based on ARGS.\nARGS is a property list where odd numbered elements are tags, and\neven numbered elements are the values to store in the tagged slot.\nIf you overload the `initialize-instance', there you will need to\ncall `shared-initialize' yourself, or you can call `call-next-method'\nto have this constructor called automatically.  If these steps are\nnot taken, then new objects of your class will not have their values\ndynamically set from ARGS." #<bytecode -0x121d888362a870fd>)(#<jsonrpc-process-connection jsonrpc-process-connection-1ff8fd5fc7ac> (:name "copilot" :events-buffer-config (:size 0) :notification-dispatcher copilot--handle-notification :process #<process copilot agent>))
  apply(#f(compiled-function (this &optional args) "Construct the new object THIS based on ARGS.\nARGS is a property list where odd numbered elements are tags, and\neven numbered elements are the values to store in the tagged slot.\nIf you overload the `initialize-instance', there you will need to\ncall `shared-initialize' yourself, or you can call `call-next-method'\nto have this constructor called automatically.  If these steps are\nnot taken, then new objects of your class will not have their values\ndynamically set from ARGS." #<bytecode -0x121d888362a870fd>) (#<jsonrpc-process-connection jsonrpc-process-connection-1ff8fd5fc7ac> (:name "copilot" :events-buffer-config (:size 0) :notification-dispatcher copilot--handle-notification :process #<process copilot agent>)))
  #f(compiled-function (&rest cnm-args) #<bytecode 0x123807b9bf933f2a>)()
  #f(compiled-function (cl--cnm conn slots) #<bytecode 0xbce6a8314a955d7>)(#f(compiled-function (&rest cnm-args) #<bytecode 0x123807b9bf933f2a>) #<jsonrpc-process-connection jsonrpc-process-connection-1ff8fd5fc7ac> (:name "copilot" :events-buffer-config (:size 0) :notification-dispatcher copilot--handle-notification :process #<process copilot agent>))
  apply(#f(compiled-function (cl--cnm conn slots) #<bytecode 0xbce6a8314a955d7>) #f(compiled-function (&rest cnm-args) #<bytecode 0x123807b9bf933f2a>) (#<jsonrpc-process-connection jsonrpc-process-connection-1ff8fd5fc7ac> (:name "copilot" :events-buffer-config (:size 0) :notification-dispatcher copilot--handle-notification :process #<process copilot agent>)))
  #f(compiled-function (&rest args) #<bytecode 0x193e76b7a7f57c1b>)(#<jsonrpc-process-connection jsonrpc-process-connection-1ff8fd5fc7ac> (:name "copilot" :events-buffer-config (:size 0) :notification-dispatcher copilot--handle-notification :process #<process copilot agent>))
  apply(#f(compiled-function (&rest args) #<bytecode 0x193e76b7a7f57c1b>) #<jsonrpc-process-connection jsonrpc-process-connection-1ff8fd5fc7ac> (:name "copilot" :events-buffer-config (:size 0) :notification-dispatcher copilot--handle-notification :process #<process copilot agent>))
  initialize-instance(#<jsonrpc-process-connection jsonrpc-process-connection-1ff8fd5fc7ac> (:name "copilot" :events-buffer-config (:size 0) :notification-dispatcher copilot--handle-notification :process #<process copilot agent>))
  #f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode -0xc41788876300f7c>)(jsonrpc-process-connection :name "copilot" :events-buffer-config (:size 0) :notification-dispatcher copilot--handle-notification :process #<process copilot agent>)
  apply(#f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode -0xc41788876300f7c>) jsonrpc-process-connection (:name "copilot" :events-buffer-config (:size 0) :notification-dispatcher copilot--handle-notification :process #<process copilot agent>))
  make-instance(jsonrpc-process-connection :name "copilot" :events-buffer-config (:size 0) :notification-dispatcher copilot--handle-notification :process #<process copilot agent>)
  copilot--start-agent()
  copilot--on-doc-focus(#<window 3 on *scratch*>)
  copilot--mode-enter()
  copilot-mode()
  copilot-diagnose()
  funcall-interactively(copilot-diagnose)
  call-interactively(copilot-diagnose record nil)
  command-execute(copilot-diagnose record)
  (progn (command-execute command 'record) (add-to-history 'extended-command-history command-name))
  (condition-case err (progn (command-execute command 'record) (add-to-history 'extended-command-history command-name)) ((debug error) (if helm-M-x-always-save-history (progn (add-to-history 'extended-command-history command-name))) (signal (car err) (cdr err))))
  (let ((prefix-arg (or helm-current-prefix-arg helm-M-x-prefix-argument)) (command-name (symbol-name command))) (condition-case err (progn (command-execute command 'record) (add-to-history 'extended-command-history command-name)) ((debug error) (if helm-M-x-always-save-history (progn (add-to-history 'extended-command-history command-name))) (signal (car err) (cdr err)))))
  (progn (setq this-command command real-this-command command) (let ((prefix-arg (or helm-current-prefix-arg helm-M-x-prefix-argument)) (command-name (symbol-name command))) (condition-case err (progn (command-execute command 'record) (add-to-history 'extended-command-history command-name)) ((debug error) (if helm-M-x-always-save-history (progn (add-to-history 'extended-command-history command-name))) (signal (car err) (cdr err))))))
  (if command (progn (setq this-command command real-this-command command) (let ((prefix-arg (or helm-current-prefix-arg helm-M-x-prefix-argument)) (command-name (symbol-name command))) (condition-case err (progn (command-execute command 'record) (add-to-history 'extended-command-history command-name)) ((debug error) (if helm-M-x-always-save-history (progn (add-to-history ... command-name))) (signal (car err) (cdr err)))))))
  helm-M-x-execute-command(copilot-diagnose)
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  helm-internal((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0x4b8c6cfc0c8cd7b>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap (keymap ...) keymap (29 . helm-M-x-toggle-short-doc) (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f12 . #f(compiled-function () ... #<bytecode 0x1ff332f25c46280>)) (f11 . #f(compiled-function () ... #<bytecode 0x1ff332f25dc5280>)) (f10 . #f(compiled-function () ... #<bytecode 0x1ff332f25dd4280>)) (f9 . #f(compiled-function () ... #<bytecode 0x1ff332f25c13280>)) (f8 . #f(compiled-function () ... #<bytecode 0x1ff332f25c02280>)) (f7 . #f(compiled-function () ... #<bytecode 0x1ff332f25c61280>)) (f6 . #f(compiled-function () ... #<bytecode 0x1ff332f25c70280>)) (f5 . #f(compiled-function () ... #<bytecode 0x1ff332f25c2f280>)) (f4 . #f(compiled-function () ... #<bytecode 0x1ff332f25c3e280>)) (f3 . #f(compiled-function () ... #<bytecode 0x1ff332f25cfd280>)) (f2 . #f(compiled-function () ... #<bytecode 0x1ff332f25cec280>)) (menu-bar keymap ...) (help keymap ...) (23 . helm-helm-yank-text-at-point-with-subkeys) (f1 . #f(compiled-function () ... #<bytecode 0x1ff332f25ccb280>)) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort (closure ... ... ...) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . #("C-j: Describe this command (keep..." 0 3 ...)) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data closure (... ... ... ... t) nil (helm-comp-read-get-candidates ... pred nil nil "")) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode 0x4b8c6cfc0c8cd7b>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap (keymap ...) keymap (29 . helm-M-x-toggle-short-doc) (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f12 . #f(compiled-function () ... #<bytecode 0x1ff332f25c46280>)) (f11 . #f(compiled-function () ... #<bytecode 0x1ff332f25dc5280>)) (f10 . #f(compiled-function () ... #<bytecode 0x1ff332f25dd4280>)) (f9 . #f(compiled-function () ... #<bytecode 0x1ff332f25c13280>)) (f8 . #f(compiled-function () ... #<bytecode 0x1ff332f25c02280>)) (f7 . #f(compiled-function () ... #<bytecode 0x1ff332f25c61280>)) (f6 . #f(compiled-function () ... #<bytecode 0x1ff332f25c70280>)) (f5 . #f(compiled-function () ... #<bytecode 0x1ff332f25c2f280>)) (f4 . #f(compiled-function () ... #<bytecode 0x1ff332f25c3e280>)) (f3 . #f(compiled-function () ... #<bytecode 0x1ff332f25cfd280>)) (f2 . #f(compiled-function () ... #<bytecode 0x1ff332f25cec280>)) (menu-bar keymap ...) (help keymap ...) (23 . helm-helm-yank-text-at-point-with-subkeys) (f1 . #f(compiled-function () ... #<bytecode 0x1ff332f25ccb280>)) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort (closure ... ... ...) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . #("C-j: Describe this command (keep..." 0 3 ...)) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data closure (... ... ... ... t) nil (helm-comp-read-get-candidates collection pred nil nil "")) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history)
  apply(helm-internal ((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0x4b8c6cfc0c8cd7b>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap ... keymap ... ... keymap ... ... ... keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort ... helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . ...) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data closure ... nil ...) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode 0x4b8c6cfc0c8cd7b>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap ... keymap ... ... keymap ... ... ... keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort ... helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . ...) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data closure ... nil ...) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history))
  helm((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0x4b8c6cfc0c8cd7b>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap (keymap ...) keymap (29 . helm-M-x-toggle-short-doc) (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f12 . #f(compiled-function () ... #<bytecode 0x1ff332f25c46280>)) (f11 . #f(compiled-function () ... #<bytecode 0x1ff332f25dc5280>)) (f10 . #f(compiled-function () ... #<bytecode 0x1ff332f25dd4280>)) (f9 . #f(compiled-function () ... #<bytecode 0x1ff332f25c13280>)) (f8 . #f(compiled-function () ... #<bytecode 0x1ff332f25c02280>)) (f7 . #f(compiled-function () ... #<bytecode 0x1ff332f25c61280>)) (f6 . #f(compiled-function () ... #<bytecode 0x1ff332f25c70280>)) (f5 . #f(compiled-function () ... #<bytecode 0x1ff332f25c2f280>)) (f4 . #f(compiled-function () ... #<bytecode 0x1ff332f25c3e280>)) (f3 . #f(compiled-function () ... #<bytecode 0x1ff332f25cfd280>)) (f2 . #f(compiled-function () ... #<bytecode 0x1ff332f25cec280>)) (menu-bar keymap ...) (help keymap ...) (23 . helm-helm-yank-text-at-point-with-subkeys) (f1 . #f(compiled-function () ... #<bytecode 0x1ff332f25ccb280>)) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort (closure ... ... ...) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . #("C-j: Describe this command (keep..." 0 3 ...)) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data closure (... ... ... ... t) nil (helm-comp-read-get-candidates ... pred nil nil "")) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode 0x4b8c6cfc0c8cd7b>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap (keymap ...) keymap (29 . helm-M-x-toggle-short-doc) (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f12 . #f(compiled-function () ... #<bytecode 0x1ff332f25c46280>)) (f11 . #f(compiled-function () ... #<bytecode 0x1ff332f25dc5280>)) (f10 . #f(compiled-function () ... #<bytecode 0x1ff332f25dd4280>)) (f9 . #f(compiled-function () ... #<bytecode 0x1ff332f25c13280>)) (f8 . #f(compiled-function () ... #<bytecode 0x1ff332f25c02280>)) (f7 . #f(compiled-function () ... #<bytecode 0x1ff332f25c61280>)) (f6 . #f(compiled-function () ... #<bytecode 0x1ff332f25c70280>)) (f5 . #f(compiled-function () ... #<bytecode 0x1ff332f25c2f280>)) (f4 . #f(compiled-function () ... #<bytecode 0x1ff332f25c3e280>)) (f3 . #f(compiled-function () ... #<bytecode 0x1ff332f25cfd280>)) (f2 . #f(compiled-function () ... #<bytecode 0x1ff332f25cec280>)) (menu-bar keymap ...) (help keymap ...) (23 . helm-helm-yank-text-at-point-with-subkeys) (f1 . #f(compiled-function () ... #<bytecode 0x1ff332f25ccb280>)) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort (closure ... ... ...) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . #("C-j: Describe this command (keep..." 0 3 ...)) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data closure (... ... ... ... t) nil (helm-comp-read-get-candidates collection pred nil nil "")) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history)
  apply(helm ((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0x4b8c6cfc0c8cd7b>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap ... keymap ... ... keymap ... ... ... keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort ... helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . ...) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data closure ... nil ...) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode 0x4b8c6cfc0c8cd7b>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap ... keymap ... ... keymap ... ... ... keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort ... helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . ...) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data closure ... nil ...) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history))
  helm(:sources (((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0x4b8c6cfc0c8cd7b>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap (keymap ...) keymap (29 . helm-M-x-toggle-short-doc) (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f12 . #f(compiled-function () ... #<bytecode 0x1ff332f25c46280>)) (f11 . #f(compiled-function () ... #<bytecode 0x1ff332f25dc5280>)) (f10 . #f(compiled-function () ... #<bytecode 0x1ff332f25dd4280>)) (f9 . #f(compiled-function () ... #<bytecode 0x1ff332f25c13280>)) (f8 . #f(compiled-function () ... #<bytecode 0x1ff332f25c02280>)) (f7 . #f(compiled-function () ... #<bytecode 0x1ff332f25c61280>)) (f6 . #f(compiled-function () ... #<bytecode 0x1ff332f25c70280>)) (f5 . #f(compiled-function () ... #<bytecode 0x1ff332f25c2f280>)) (f4 . #f(compiled-function () ... #<bytecode 0x1ff332f25c3e280>)) (f3 . #f(compiled-function () ... #<bytecode 0x1ff332f25cfd280>)) (f2 . #f(compiled-function () ... #<bytecode 0x1ff332f25cec280>)) (menu-bar keymap ...) (help keymap ...) (23 . helm-helm-yank-text-at-point-with-subkeys) (f1 . #f(compiled-function () ... #<bytecode 0x1ff332f25ccb280>)) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort (closure ... ... ...) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . #("C-j: Describe this command (keep..." 0 3 ...)) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data closure (... ... ... ... t) nil (helm-comp-read-get-candidates ... pred nil nil "")) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode 0x4b8c6cfc0c8cd7b>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap (keymap ...) keymap (29 . helm-M-x-toggle-short-doc) (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (f12 . #f(compiled-function () ... #<bytecode 0x1ff332f25c46280>)) (f11 . #f(compiled-function () ... #<bytecode 0x1ff332f25dc5280>)) (f10 . #f(compiled-function () ... #<bytecode 0x1ff332f25dd4280>)) (f9 . #f(compiled-function () ... #<bytecode 0x1ff332f25c13280>)) (f8 . #f(compiled-function () ... #<bytecode 0x1ff332f25c02280>)) (f7 . #f(compiled-function () ... #<bytecode 0x1ff332f25c61280>)) (f6 . #f(compiled-function () ... #<bytecode 0x1ff332f25c70280>)) (f5 . #f(compiled-function () ... #<bytecode 0x1ff332f25c2f280>)) (f4 . #f(compiled-function () ... #<bytecode 0x1ff332f25c3e280>)) (f3 . #f(compiled-function () ... #<bytecode 0x1ff332f25cfd280>)) (f2 . #f(compiled-function () ... #<bytecode 0x1ff332f25cec280>)) (menu-bar keymap ...) (help keymap ...) (23 . helm-helm-yank-text-at-point-with-subkeys) (f1 . #f(compiled-function () ... #<bytecode 0x1ff332f25ccb280>)) (8 keymap ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort (closure ... ... ...) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . #("C-j: Describe this command (keep..." 0 3 ...)) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data closure (... ... ... ... t) nil (helm-comp-read-get-candidates collection pred nil nil "")) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) :prompt "M-x " :buffer "*helm M-x*" :history helm-M-x-input-history :truncate-lines t)
  (progn (setq current-prefix-arg nil) (helm :sources sources :prompt prompt :buffer "*helm M-x*" :history 'helm-M-x-input-history :truncate-lines t))
  (unwind-protect (progn (setq current-prefix-arg nil) (helm :sources sources :prompt prompt :buffer "*helm M-x*" :history 'helm-M-x-input-history :truncate-lines t)) (helm-M-x--unwind-forms))
  (let* ((pred (or predicate #'commandp)) (helm-fuzzy-sort-fn #'(lambda (candidates _source) (helm-fuzzy-matching-default-sort-fn-1 candidates t))) (sources (list (helm-make-source "Emacs Commands history" 'helm-M-x-class :data #'(lambda nil (helm-comp-read-get-candidates ... pred nil nil "")) :fuzzy-match helm-M-x-fuzzy-match) (helm-make-source "Emacs Commands" 'helm-M-x-class :data #'(lambda nil (helm-comp-read-get-candidates collection pred nil nil "")) :fuzzy-match helm-M-x-fuzzy-match))) (prompt (concat (cond ((eq helm-M-x-prefix-argument '-) "- ") ((and (consp helm-M-x-prefix-argument) (eq ... 4)) "C-u ") ((and (consp helm-M-x-prefix-argument) (integerp ...)) (format "%d " (car helm-M-x-prefix-argument))) ((integerp helm-M-x-prefix-argument) (format "%d " helm-M-x-prefix-argument))) "M-x "))) (setq helm-M-x--timer (run-at-time 1 0.1 #'helm-M-x--notify-prefix-arg)) (add-hook 'helm-move-selection-after-hook #'helm-M-x--move-selection-after-hook) (add-hook 'helm-before-action-hook #'helm-M-x--before-action-hook) (if (and sources helm-M-x-reverse-history) (progn (setq sources (nreverse sources)))) (unwind-protect (progn (setq current-prefix-arg nil) (helm :sources sources :prompt prompt :buffer "*helm M-x*" :history 'helm-M-x-input-history :truncate-lines t)) (helm-M-x--unwind-forms)))
  helm-M-x-read-extended-command([python-imenu-format-parent-item-label table--measure-max-width vc-src-responsible-p body-height json-obj ensime-compile-result-buffer-name jsonrpc-name org-clock-get-sum-start speedbar-check-vc-this-line sp--looking-at ivy-default-view-name ein:notebook-url helm-completing-read-inbuffer-default-handler eshell-mv-interactive-query gnus-article-nndoc-name &error rng-parse-validate-file C-c speedbar-file-regexp racket-insert-closing-bracket web-mode-extra-snippets edebug-mode-on-hook :reveal-slide-number transient:magit-diff-refresh:--irreversible-delete er/looking-back-max copilot-login web-mode-is-html-string rule-regexp :where *table--cell-kill-paragraph :odt-styles-file gdb-thread-number :mac actionmsg vc-bzr-shelve-menu rng-match-infer-start-tag-namespace Above edconf-custom-hooks int-file-name plugin-changed use-package-handler/:interpreter helm-grep-save-results-1 article-fill-long-lines smime-buffer-as-string-region zoo ein:query-get-cookies shell-maker--write-input-ring-history image-dired-list-tags bibtex-text-in-string helm-debug-output-function ...])
  (if (or defining-kbd-macro executing-kbd-macro) (helm-M-x--vanilla-M-x) (helm-M-x-read-extended-command obarray))
  helm-M-x(nil)
  funcall-interactively(helm-M-x nil)
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

Copilot.el still works on my Ubuntu linux machine.

**Comment by zerolfx** [comment]
See #232

**Comment by tninja** [comment]
@zerolfx You are right. Upgrade jsonrpc to 1.0.24 works. Thanks for helping. Close this.
