### ISSUE TITLE
Consider more maintainers?

### ISSUE THREAD

**Issue by jcs090218** [copilot-emacs/copilot.el#246]
Thanks for this awesome package! 🚀 

I wonder does this package needs more maintainers? If so, I would like volunteer myself.

Regarding myself, I serve as the primary maintainer for `emacs-dashboard` and one of the maintainers for `lsp-mode`. I have developed over a hundred Emacs packages. Hope I am qualified to help maintain this package.

I've already opened my first PR to this repo in #245. :)

**Comment by jcs090218** [comment]
Done, I've opened a feature request in #247.

**Comment by zerolfx** [comment]
@emil-vdw I've made you an owner of the organization. You'll be able to grant additional write access to contributors and even add new owners in the future.
@jcs090218 It's very welcome. We do need more hands!

**Comment by jcs090218** [comment]
> It's very welcome. We do need more hands!

I've made a feature request in #247. Hope this will help this package get published to MELPA soon.
