### ISSUE TITLE
Change the org icon?

### ISSUE THREAD

**Issue by jcs090218** [copilot-emacs/copilot.el#254]
I recommend changing the organization's image to something else so it's easier to differentiate it from other organizations. 🤔 

Maybe the image below? (Randomly found this on the internet)

![emacs-copilot](https://github.com/copilot-emacs/copilot.el/assets/8685505/8d463a0f-f7e4-4338-ba9b-081a777be903)

**Comment by emil-vdw** [comment]
I am fine with this as long as the asset is not copyrighted.

**Comment by jcs090218** [comment]
The two logos are copyrighted, but the policy didn't restrict their use as long this project is not for commercial use. 🤔

**Comment by emil-vdw** [comment]
Do you have a link to the original source?

**Comment by jcs090218** [comment]
I got the image from https://robert.kra.hn/posts/2023-02-22-copilot-emacs-setup/.

**Comment by emil-vdw** [comment]
I have emailed the author for his permission. I will report back.

**Comment by jcs090218** [comment]
Any update on this? 🤔

**Comment by emil-vdw** [comment]
No response.

**Comment by jcs090218** [comment]
I think the logo creator is on GitHub too? 🤔 

cc @rksm Sorry if you aren't the logo creator. We want the creator's permission to use the logo image for this org.

**Comment by rksm** [comment]
Hi folks, my apologies I was a bit buried in work and missed this. Please feel free to use the image, no attribution necessary.

Btw, copilot.el is just really really great, it helps immensely while not getting in the way too much. I can't imagine live without it anymore. Thanks to everyone building and maintaining this!

**Comment by jcs090218** [comment]
@emil-vdw Do you have time for this? :)

**Comment by emil-vdw** [comment]
@jcs090218 Will do.

Thanks @rksm. Very kind of you!
