### ISSUE TITLE
PR #259 breaks startup

### ISSUE THREAD

**Issue by jkl1337** [copilot-emacs/copilot.el#262]
The commit in PR #259 has a number of problems and breaks emacs startup in most cases especially if using something like straight.el.

- `package-get-descriptor` is emacs 28.1 and above, so the Package-Requires should be updated. (Suggest using package-lint to avoid this).
- `(require 'package)` is missing so compilation breaks.

More troublesome is that `package-get-descriptor` only works if the descriptor is fetched and loaded, they do not need to be loaded normally to use/require a package. 
Is there a way to test for the needed features without pulling package metadata?

**Comment by jcs090218** [comment]
Sorry about this. I've opened the fix in #260x. Can you see if it works?

**Comment by jcs090218** [comment]
> The commit in PR https://github.com/copilot-emacs/copilot.el/pull/259 has a number of problems and breaks emacs startup in most cases especially if using something like straight.el.

I am a little confused. `straight.el` is not the standard way to load Emacs packages, and it should at least handle things like this (compatible to `package.el`)? Or else, packages would have to include `(require 'package)` everywhere. 🤔

**Comment by jkl1337** [comment]
Sorry, those are two different issues.
The reference to straight.el is just pointing out that packages are not necessarily going to come from ELPA so `package-get-descriptor` is not going to work.

`(require 'package)` is needed because you are using a `package` package provided function (`package-get-descriptor` or `package-get-version`) in the fixed version.

**Comment by jcs090218** [comment]
> The reference to straight.el is just pointing out that packages are not necessarily going to come from ELPA so package-get-descriptor is not going to work.

Got it! I've removed it.

> (require 'package) is needed because you are using a package library provided function (package-get-descriptor or package-get-version) in the fixed version.

I've added the `(require 'package)`. I believed this is best practice since we are using some of functions in this module. Thank you for your report!
