### ISSUE TITLE
Documentation seems to be missing `f` dependency in installation instructions

### ISSUE THREAD

**Issue by aezarebski** [copilot-emacs/copilot.el#269]
https://github.com/copilot-emacs/copilot.el/blob/0e24423cfef2993b3a9633c8cbb654079f2652a9/readme.md?plain=1#L151

The package `f` is not listed as something you need to have installed but [this](https://github.com/copilot-emacs/copilot.el/blob/0e24423cfef2993b3a9633c8cbb654079f2652a9/copilot.el#L18) line suggests it might be needed. Please excuse the noise if this is not the case, and thanks for writing such a helpful package!

**Comment by emil-vdw** [comment]
@aezarebski you're right and this should be added to the readme.
