### ISSUE TITLE
How to hide *copilot events* buffer when copilot-log-max is 0

### ISSUE THREAD

**Issue by zhenhua-wang** [copilot-emacs/copilot.el#275]
Currently, emacs would open an empty *copilot events* buffer when copilot-log-max is 0. I wonder if there is a way to hide it?

**Comment by emil-vdw** [comment]
This is internal to `jsonrpc`. You could advise `jsonrpc--debug` and filter out calls for the copilot connection for instance.

**Comment by zhenhua-wang** [comment]
Thanks for replying. However, this does not seem to work. I even tried disable `jsonrpc--debug` completely and the `*copilot events*` buffer still showed up.

Here is how I disabled  `jsonrpc--debug`.

```
(fset #'jsonrpc--debug #'ignore)
```
