### ISSUE TITLE
Warning (copilot): copilot--infer-indentation-offset found no mode-specific indentation offset.

### ISSUE THREAD

**Issue by mentamortem** [copilot-emacs/copilot.el#276]
![image](https://github.com/copilot-emacs/copilot.el/assets/119333794/d863c54e-0164-40de-bb29-57cbc3958e42)

**Comment by jcs090218** [comment]
It's a nice warning from this package. 🤔 

https://github.com/copilot-emacs/copilot.el/blob/fd4d7e8c1e95aa9d3967b19905c9b8c3e03f6a5c/copilot.el#L370-L371

**Comment by tophat8855** [comment]
You can disable the warning or add customize the indentation alist as per this PR: https://github.com/copilot-emacs/copilot.el/pull/230

**Comment by riclima** [comment]
@tophat8855 thanks for the info. I was looking for a way to turn this warning off as well. For some reason, I get this warning every time I run `M-x` and type a command.

**Comment by mentamortem** [comment]
Thank you!
