### ISSUE TITLE
Can I use a token for authentication?

### ISSUE THREAD

**Issue by madorian** [copilot-emacs/copilot.el#277]
I run emacs on a different system, so it would be easier if I could use some kind of token for authentication. Is that possible?

**Comment by emil-vdw** [comment]
Unfortunately not with the current implementation. Looks like the meat and potatoes of the auth flow is handled by the agent (from copilot.vim) not maintained by us.

**Comment by madorian** [comment]
ok, but can I somehow specify which browser command to open, so that I can use a specific profile of the browser?

**Comment by emil-vdw** [comment]
We use the `browse-url` to open the verification link so would be worth reading up on the docs of that.
Looks like you can customize `browse-url-browser-function`, not sure if this can achieve exactly what you're looking for? (haven't tested this myself)

**Comment by madorian** [comment]
I will try, but how long can I expect this login to be valid, until I have to login again?
