### ISSUE TITLE
No `copilot-login` after install on doomemacs

### ISSUE THREAD

**Issue by gui-salome** [copilot-emacs/copilot.el#289]
Running a fresh install of Emacs 29.3 and doomemacs.
After updating `packages.el` with:
```
(package! copilot
  :recipe (:host github :repo "copilot-emacs/copilot.el" :files ("*.el" "dist")))
```
And running `doom sync` and restarting Emacs, I attempted to run `M-x copilot-login`. However, no function with that name is available. The only functions I see are:
<img width="758" alt="Screenshot 2024-03-28 at 3 56 10 PM" src="https://github.com/copilot-emacs/copilot.el/assets/68299186/5b9cb4a1-2c26-4a98-9bf9-d65dee85bd7e">

Am I missing something in the install? 

Thanks!

**Comment by jcs090218** [comment]
Is there any backtrace? Try `M-x copilot-install-server`.

**Comment by gui-salome** [comment]
Oh you are supposed to run `copilot-install-server` first. I didn't realize that, thank you.
After running `copilot-install-server` worked without any issues, and then I was able to find all other functions.

**Comment by Packjackisback** [comment]
Maybe add this to the readme?

**Comment by jcs090218** [comment]
Yes, we should add it to the readme.
