### ISSUE TITLE
Copilot Chat

### ISSUE THREAD

**Issue by jcubic** [copilot-emacs/copilot.el#293]
I just found about Copilot Chat in VS Code. I'm not able to find any information about using it in Emacs. Do you think it's a good idea to add support for it to this library?

I was thinking maybe integrating (or taking part from) [emacs-openai/chatgpt](https://github.com/emacs-openai/chatgpt)

Here is a video about this feature (pined to the part about the Chat).

https://www.youtube.com/live/h6U_cHRs2cM?si=PJ9GwtHBgNGpMzMh&t=1706

**Comment by jcs090218** [comment]
> I was thinking maybe integrating (or taking part from) emacs-openai/chatgpt

I'm one of the maintainers of this package, and I'm the author of chatgpt. Glad you found these packages. :) 

Does VSCode Chat use the same protocol as chatgpt? If not, it would probably have to be integrated by ourselves. 🤔

cc @emil-vdw WDYT?

**Comment by jcubic** [comment]
I have no idea, I don't use VS Code and just found about copilot chat.

**Comment by jcs090218** [comment]
Close this for duplicate #199.
