### ISSUE TITLE
Wrong name for Clojure mode?

### ISSUE THREAD

**Issue by slipset** [copilot-emacs/copilot.el#295]
Reading through the source code I notice that the name for Cojure mode might be misspelled [here](https://github.com/copilot-emacs/copilot.el/blob/main/copilot.el#L426)? I believe this should be `clojure` and not `clojurec`?

**Comment by jcs090218** [comment]
You are right. I've opened a fix in #296.

**Comment by ComedyTomedy** [comment]
Might want to re-open this - Clojure uses 3 modes: clojure-mode, clojurescript-mode, and clojurec-mode. Clojurec is for files that are compatible with both the 2 other dialects.

I suspect all 3 should be included.

Obviously the fix is pretty trivial :)
