### ISSUE TITLE
Not getting suggestions while typing

### ISSUE THREAD

**Issue by mikeiwi** [copilot-emacs/copilot.el#301]
Hi folks, I recently installed `copilot-emacs` and found out that I never get any suggestion as I type. I guess that's the expected behavior, isn't it?
When I run `copilot-complete` I get the suggestion with no problem.

I haven't set any `copilot-idle-delay`, I just followed the instructions in the repo for [doom emacs](https://github.com/copilot-emacs/copilot.el?tab=readme-ov-file#example-for-doom-emacs) and added nothing more.

The only workaround I have is that I mapped `copilot-complete` to `C-tab`, so I can trigger some suggestions manually. But I think it would be interesting if they appear automatically as I type.

I'm using emacs 28.2

Thank you for your help.

**Comment by zerolfx** [comment]
Did you have `copilot-mode` enabled?

**Comment by mikeiwi** [comment]
Yes, I checked that as well.
In fact, when `copilot-mode` is disabled I get "No completion is available" whenever I run `copilot-complete`.

**Comment by fpl9000** [comment]
`copilot-idle-delay` is used like this:
```
(when (numberp copilot-idle-delay)
      (setq copilot--post-command-timer
            (run-with-idle-timer copilot-idle-delay
                                 nil
                                 #'copilot--post-command-debounce
                                 (current-buffer))))
```
So verify that `copilot-idle-delay` is in fact set to `0` (the default value). And try some values larger than `0`.

**Comment by oikawa-yusuke** [comment]
I had the same issue. I resolved it by referring to the following:

https://github.com/copilot-emacs/copilot.el/issues/123

Specifically, the issue was resolved by setting copilot-enable-predicates to nil.

**Comment by ovistoica** [comment]
Yes, the same solved it for me too. 
`(setq copilot-enable-predicates nil)` fixes the issue

**Comment by mikeiwi** [comment]
Sorry for coming back this late. 
Just tested and, as @ovistoica and @oikawa-yusuke mentioned, `(setq copilot-enable-predicates nil)` fixed the issue for me as well. I'm closing this issue. 

Thank you everyone!
